const complaints = [
    {
      id: 1,
      userID: 1,
      images: ["https://via.placeholder.com/300", "https://via.placeholder.com/300"],
      audio_note: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      title: "Broken Streetlight",
      description: "The streetlight near my house has been broken for 2 weeks.",
      location: {
        latitude: 18.5913,
        longitude: 73.7381,
        geohash: 'te71z7w'
      },
      date: "2025-09-02",
      date_of_publishing: "2025-09-03",
      time_published: "10:00:00",
      status: "Pending",
      concerned_department: "Electrical",
      approved: true,
      tasklist_assigned: true,
      tasklist: [
        { text: "Assess the damage", checked: true },
        { text: "Order new parts", checked: true },
        { text: "Schedule repair", checked: false },
      ],
      upvotes: 15,
      downvotes: 2,
      department_response: "We have received your complaint and are working on it.",
    },
    {
      id: 2,
      userID: 1,
      images: ["https://via.placeholder.com/300"],
      audio_note: null,
      title: "Overflowing Garbage Bin",
      description: "Garbage bin near Sector 14 has not been cleared in 3 days.",
      location: {
        latitude: 18.59,
        longitude: 73.74,
        geohash: 'te71zt3'
      },
      date: "2025-09-01",
      date_of_publishing: "2025-09-01",
      time_published: "14:30:00",
      status: "Resolved",
      concerned_department: "Garbage",
      approved: true,
      tasklist_assigned: true,
      tasklist: [
        { text: "Dispatch garbage truck", checked: true },
        { text: "Clear the garbage", checked: true },
        { text: "Sanitize the area", checked: true },
      ],
      upvotes: 10,
      downvotes: 0,
      department_response: "The issue has been resolved.",
    },
    {
        id: 3,
        userID: 2,
        images: [],
        audio_note: null,
        title: "Pothole on Main Street",
        description: "A large pothole has formed on Main Street, causing traffic issues.",
        location: {
            latitude: 18.60,
            longitude: 73.75,
            geohash: 'te72p04'
        },
        date: "2025-08-28",
        date_of_publishing: "2025-08-28",
        time_published: "09:15:00",
        status: "Pending",
        concerned_department: "Municipal",
        approved: true,
        tasklist_assigned: false,
        tasklist: [],
        upvotes: 25,
        downvotes: 1,
        department_response: "",
    },
    {
        id: 4,
        userID: 1,
        images: ["https://via.placeholder.com/300"],
        audio_note: null,
        title: "Water Leakage",
        description: "There's a constant water leakage on the corner of Elm Street.",
        location: {
            latitude: 18.58,
            longitude: 73.73,
            geohash: 'te71x S'
        },
        date: "2025-09-04",
        date_of_publishing: "2025-09-04",
        time_published: "11:00:00",
        status: "Pending",
        concerned_department: "Water",
        approved: false,
        tasklist_assigned: false,
        tasklist: [],
        upvotes: 5,
        downvotes: 0,
        department_response: "",
    }
  ];

  export default complaints;
